// Optional browser check: npm install --no-save playwright
import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const errors = [];
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
context.setDefaultTimeout(12000);
const teacher = await context.newPage(), anna = await context.newPage(), max = await context.newPage();
for (const page of [teacher, anna, max]) page.on('pageerror', e => errors.push(e.message));
const base = process.env.TEST_URL || 'http://localhost:3100';
try {
  await mkdir('test-results', { recursive: true });
  await teacher.goto(base, { waitUntil: 'domcontentloaded' });
  await teacher.getByRole('button', { name: 'Question word: WHAT. Rotate cube' }).click();
  await teacher.getByRole('button', { name: 'Question word: WHEN. Rotate cube' }).waitFor();
  await teacher.screenshot({ path: 'test-results/home.png', fullPage: true });
  await teacher.getByRole('button', { name: 'Create a room' }).click();
  await teacher.locator('#room-code').waitFor();
  const code = await teacher.locator('#room-code').textContent();
  for (const [page, name] of [[anna, 'Anna Elizabeth'], [max, 'Max Alexander']]) {
    await page.goto(`${base}/?room=${code}`, { waitUntil: 'domcontentloaded' });
    await page.getByLabel('Your name').fill(name);
    await page.getByRole('button', { name: 'Join room' }).click();
    await page.locator('#student-name').waitFor();
    assert.equal(await page.locator('#student-name').textContent(), name);
  }
  await anna.getByRole('button', { name: 'Question word: WHAT. Rotate cube' }).click();
  await anna.getByRole('button', { name: 'Auxiliary: DO. Rotate cube', exact: true }).click();
  for (let i = 0; i < 3; i++) await anna.locator('.cube-control').nth(2).click();
  for (let i = 0; i < 2; i++) await anna.locator('.cube-control').nth(3).click();
  await teacher.locator('.student-card').filter({ hasText: 'Anna' }).locator('[aria-label="Verb: READ"]').waitFor();
  const annaCard = teacher.locator('.student-card').filter({ hasText: 'Anna' });
  assert.equal(await annaCard.locator('.cube-control').nth(2).getAttribute('aria-label'), 'Subject: SHE');
  assert.equal(await max.locator('.cube-control').nth(0).getAttribute('aria-label'), 'Question word: WHAT. Rotate cube');
  for (let i = 0; i < 12; i++) await anna.locator('.cube-control').nth(0).click();
  assert.equal(await anna.locator('.cube-control').nth(0).getAttribute('aria-label'), 'Question word: WHEN. Rotate cube');
  await anna.reload({ waitUntil: 'domcontentloaded' });
  await anna.getByRole('button', { name: 'Subject: SHE. Rotate cube' }).waitFor();
  await teacher.screenshot({ path: 'test-results/teacher.png', fullPage: true });
  await anna.screenshot({ path: 'test-results/student.png', fullPage: true });
  await anna.setViewportSize({ width: 768, height: 1024 });
  await anna.screenshot({ path: 'test-results/tablet.png', fullPage: true });
  assert.equal(await anna.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  assert.equal(await anna.locator('.cube-label').count(), 0);
  assert.equal(await teacher.locator('.cube-label').count(), 0);
  assert.equal(await anna.getByRole('button', { name: 'NEW ROUND' }).count(), 0);
  await anna.locator('#bell').click();
  assert.equal(await anna.locator('#my-cubes button:disabled').count(), 4);
  await teacher.locator('.student-card').filter({ hasText: 'Anna Elizabeth' }).getByText('🔔 Finished · Locked').waitFor();
  assert.equal(await anna.locator('#partner-question').isVisible(), false);
  assert.equal(await max.locator('#partner-question').isVisible(), false);
  await max.locator('#my-cubes button').first().click();
  await anna.reload({ waitUntil: 'domcontentloaded' });
  await anna.locator('#my-cubes button:disabled').first().waitFor();
  await max.locator('#bell').click();
  await anna.locator('#partner-question').waitFor();
  await max.locator('#partner-question').waitFor();
  assert.equal(await max.locator('#my-cubes button:disabled').count(), 4);
  assert.equal(await anna.locator('#partner-question h2').textContent(), 'Max Alexander');
  await anna.setViewportSize({ width: 1440, height: 1000 });
  await anna.screenshot({ path: 'test-results/compare.png', fullPage: true });
  await teacher.screenshot({ path: 'test-results/teacher-finished.png', fullPage: true });
  await teacher.getByRole('button', { name: 'NEW ROUND' }).click();
  await anna.locator('#my-cubes button:enabled').first().waitFor();
  await max.locator('#my-cubes button:enabled').first().waitFor();
  assert.equal(await anna.locator('#partner-question').isVisible(), false);
  assert.equal(await max.locator('#partner-question').isVisible(), false);
  assert.equal(await teacher.locator('#room-code').textContent(), code);
  await anna.locator('#my-cubes button').first().click();
  await anna.locator('#bell').click();
  await max.locator('#bell').click();
  await anna.locator('#partner-question').waitFor();
  await max.locator('#partner-question').waitFor();
  assert.deepEqual(errors, []);
  console.log('Browser check passed: live cubes, full names, no labels, bell locks, private waiting, reveal, teacher-only new round, second round, reload and tablet.');
} catch (error) {
  console.log(errors);
  console.log(await anna.locator('body').innerText());
  throw error;
} finally { await browser.close(); }
